# Generated by Django 4.1.4 on 2023-01-15 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pimpin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='meeting_place',
            field=models.CharField(help_text='Desired location to your Pawfrence', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='meeting_time',
            field=models.DateTimeField(help_text='YYYY-MM-DD HH:MM', max_length=16),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(help_text='Descriptive tag', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pimpin_app.message')),
            ],
        ),
    ]
