# Generated by Django 4.1.4 on 2023-01-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimpin_app', '0002_alter_message_meeting_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('pet_info', models.CharField(max_length=200)),
                ('home_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='meeting_place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='meeting_time',
            field=models.DateTimeField(max_length=16),
        ),
        migrations.AlterField(
            model_name='tag',
            name='body',
            field=models.TextField(max_length=25),
        ),
    ]
