# Generated by Django 4.1.4 on 2023-01-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimpin_app', '0002_alter_message_meeting_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='message',
            name='meeting_place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='meeting_time',
            field=models.DateTimeField(max_length=16),
        ),
        migrations.AlterField(
            model_name='tag',
            name='body',
            field=models.TextField(max_length=25),
        ),
    ]
