# Generated by Django 4.1.4 on 2023-01-19 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pimpin_app', '0003_post_alter_message_meeting_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pimpin_app.message'),
        ),
    ]
