# Generated by Django 4.1.4 on 2023-01-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pimpin_app', '0003_remove_message_user_id_alter_message_meeting_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
    ]
