# Generated by Django 4.1.4 on 2023-01-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimpin_app', '0004_remove_post_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='body',
            field=models.TextField(max_length=50),
        ),
    ]
