# Generated by Django 4.1.4 on 2023-03-02 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pimpin_app', '0005_alter_tag_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('adoptees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='pimpin_app.tag')),
            ],
        ),
    ]
