# Generated by Django 4.1.4 on 2023-03-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimpin_app', '0006_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='pimpin_main\\pimpin_app\\static\\images\\pawprints.jpg', upload_to='images/'),
        ),
    ]
